name: Living-Documentation-Pipeline
pipeline:
  - skill: api-doc-generator
    params: { dir: 'work/sample-check/src', out: 'work/extracted-api.adf.json' }
  - skill: word-artisan
    params: { input: 'README.md', out: 'work/Technical_Specification_v3.docx' }
