#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

/**
 * distill_wisdom.cjs
 * Analyzes mission evidence and extracts reusable insights into the knowledge base.
 */

const rootDir = path.resolve(__dirname, '..');
const wisdomDir = path.join(rootDir, 'knowledge/incidents');

if (!fs.existsSync(wisdomDir)) {
  fs.mkdirSync(wisdomDir, { recursive: true });
}

function distill(missionDir) {
  const missionId = path.basename(missionDir);
  const reportPath = path.join(missionDir, 'ace-report.json');
  const logPath = path.join(missionDir, 'execution.log');

  if (!fs.existsSync(reportPath)) return null;

  try {
    const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));
    let logContent = '';
    if (fs.existsSync(logPath)) {
      logContent = fs.readFileSync(logPath, 'utf8');
    }

    const isSuccess = report.status === 'success' || logContent.includes('[SUCCESS]');
    const category = isSuccess ? 'success-pattern' : 'incident-recovery';

    const wisdom = {
      missionId,
      timestamp: report.timestamp || new Date().toISOString(),
      category,
      intent: report.intent || 'Unknown',
      outcome: isSuccess ? 'Victory Conditions Met' : 'Execution Failed/Incomplete',
      summary: report.summary || 'No summary provided in ACE report.',
      keyLessons: extractLessons(logContent, isSuccess),
      roleInvolved: report.role || 'Unknown'
    };

    const fileName = `distilled-${missionId}-${Date.now()}.md`;
    const filePath = path.join(wisdomDir, fileName);

    const content = `---
mission_id: ${wisdom.missionId}
timestamp: ${wisdom.timestamp}
category: ${wisdom.category}
role: ${wisdom.roleInvolved}
---

# Wisdom Distilled from Mission ${wisdom.missionId}

## 🎯 Intent
${wisdom.intent}

## 📊 Outcome
**${wisdom.outcome}**

## 📝 Summary
${wisdom.summary}

## 💡 Key Lessons & Observations
${wisdom.keyLessons}

---
*Generated by Gemini Wisdom Distiller*
`;

    fs.writeFileSync(filePath, content);
    return filePath;
  } catch (err) {
    console.error(`[Distiller] Error processing ${missionId}: ${err.message}`);
    return null;
  }
}

function extractLessons(log, isSuccess) {
  const lines = log.split('\n');
  const lessons = [];
  
  if (!isSuccess) {
    const errorLines = lines.filter(l => l.includes('ERROR') || l.includes('fail')).slice(-5);
    if (errorLines.length > 0) {
      lessons.push('### Failure Root Cause (Estimated)');
      lessons.push(errorLines.join('\n'));
    }
  }

  const observations = lines.filter(l => l.includes('Observation') || l.includes('Finding'));
  if (observations.length > 0) {
    lessons.push('### Key Observations');
    lessons.push(observations.slice(0, 5).join('\n'));
  }

  if (lessons.length === 0) {
    return 'Execution completed without specific logged observations.';
  }

  return lessons.join('\n\n');
}

if (require.main === module) {
  const target = process.argv[2];
  if (target && fs.existsSync(target)) {
    const result = distill(target);
    if (result) console.log(`[SUCCESS] Wisdom saved to ${result}`);
  }
}

module.exports = { distill };
