/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface CorporateDesignADF {
  kind: 'corporate-design-adf';
  version: string;
  client: {
    name: string;
    short_name: string;
    copyright?: string;
    confidentiality?: 'public' | 'internal' | 'confidential' | 'restricted';
  };
  slide_size: {
    width_emu: number;
    height_emu: number;
    aspect_ratio: '16:9' | '4:3' | '16:10';
  };
  color_scheme: {
    primary: string;
    secondary?: string;
    background: string;
    text_primary: string;
    text_secondary?: string;
    text_on_primary?: string;
    accent?: string[];
    semantic?: {
      success?: string;
      warning?: string;
      danger?: string;
      info?: string;
    };
  };
  typography: {
    title: FontSpec;
    body: FontSpec;
    caption?: FontSpec;
    code?: FontSpec;
    bullet?: {
      font?: string;
      char?: string;
    };
  };
  layouts: Layout[];
  assets?: {
    logo?: Asset;
    logo_white?: Asset;
    cover_background?: Asset;
    icon_set?: Asset;
  };
  render_hints?: {
    [k: string]: unknown;
  };
}

export interface FontSpec {
  family_ja?: string;
  family_latin?: string;
  family_fallback?: string;
  size_pt?: number;
  weight?: 'normal' | 'bold';
  line_spacing_pct?: number;
}

export interface Layout {
  id: string;
  name: string;
  role: 'cover' | 'section' | 'content' | 'content_two_col' | 'blank' | 'closing';
  description?: string;
  elements?: Element[];
}

export interface Element {
  type:
    | 'shape'
    | 'image'
    | 'text'
    | 'placeholder'
    | 'logo'
    | 'copyright'
    | 'page_number'
    | 'confidential_label';
  description?: string;
  placeholder_type?: 'title' | 'subtitle' | 'body' | 'custom';
  shape?: string;
  fill_color?: string;
  font_size_pt?: number;
  font_color?: string;
  font_weight?: 'normal' | 'bold';
  align?: 'left' | 'center' | 'right';
  valign?: 'top' | 'middle' | 'bottom';
  border?: {
    color?: string;
    width_pt?: number;
  };
  position?: {
    x_emu?: number;
    y_emu?: number;
    w_emu?: number;
    h_emu?: number;
  };
}

export interface Asset {
  path: string;
  description?: string;
}
