/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface OperatorInteractionPacket {
  kind: 'operator-interaction-packet';
  interaction_type: 'clarification' | 'execution-preview' | 'status-summary';
  headline: string;
  summary: string;
  readiness?: string;
  confidence?: number;
  questions?: {
    id: string;
    question: string;
    reason: string;
    default_assumption?: string;
    impact?: string;
    [k: string]: unknown;
  }[];
  next_actions?: {
    id: string;
    action: string;
    reason?: string;
    [k: string]: unknown;
  }[];
  llm_touchpoints?: {
    stage: string;
    purpose: string;
    output_contract: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
