/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface PresentationPreferenceProfile {
  kind: 'presentation-preference-profile';
  profile_id: string;
  scope?: 'proposal' | 'internal_share' | 'briefing' | 'marketing' | 'training' | 'default';
  theme_selection_policy: {
    decision_mode: 'auto_with_preflight' | 'ask_when_uncertain' | 'always_confirm_theme';
    ask_user_when: (
      | 'audience_unclear'
      | 'brand_alignment_unclear'
      | 'chart_density_unclear'
      | 'executive_tone_unclear'
      | 'new_deck_category'
      | 'user_requested_precheck'
    )[];
    default_theme_hint?: string;
  };
  brief_question_sets: {
    label: string;
    deck_purposes?: (
      | 'proposal'
      | 'internal_share'
      | 'briefing'
      | 'marketing'
      | 'training'
      | 'comparison'
    )[];
    questions: [string, ...string[]];
    notes?: string;
  }[];
  theme_sets: {
    label: string;
    deck_purposes?: (
      | 'proposal'
      | 'internal_share'
      | 'briefing'
      | 'marketing'
      | 'training'
      | 'comparison'
    )[];
    theme_hint: string;
    design_traits?: (
      | 'executive'
      | 'brand_aligned'
      | 'minimal'
      | 'chart_heavy'
      | 'narrative'
      | 'technical'
      | 'teaching'
      | 'dense'
    )[];
    notes?: string;
  }[];
}
