/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface ProposalStorylineADF {
  kind: 'proposal-storyline-adf';
  title: string;
  client?: string;
  core_message?: string;
  slides: {
    id: string;
    title: string;
    objective: string;
    body?: string[];
    visual?: string;
  }[];
}
