/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run `pnpm generate:types` to regenerate this file.
 */

export interface SystemStatusReport {
  kind: 'system-status-report';
  scope: string;
  headline: string;
  summary: string;
  findings: {
    id: string;
    severity: 'info' | 'warning' | 'error';
    message: string;
    detail?: string;
    [k: string]: unknown;
  }[];
  next_actions?: {
    id: string;
    priority: 'now' | 'next' | 'later';
    action: string;
    reason?: string;
    [k: string]: unknown;
  }[];
  metrics?: {
    [k: string]: unknown;
  };
  sources?: string[];
  [k: string]: unknown;
}
